server:
  port: 8080

debug: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huanle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效


#发送邮件
  mail:
    host: smtp.qq.com             #发送邮件服务器
    username: 1076274231@qq.com    #QQ邮箱
    password: rukitycxopueihie     #客户端授权码
    protocol: smtp                 #发送邮件协议
    default-encoding: UTF-8        #编码类型

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.huanle.entity  # 注意：对应实体类的路径

  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名转换



#配置上传文件的最大值
servlet:
  multipart:
    enabled: true
    max-file-size: 5MB
    max-request-size: 25MB

#自定义文件上传路径
web:
  upload-path: /imgUpload/




